@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3MjQ0YTlmMC00YjA3LTRiYTUtYWJmOC1mMmU1OWVmYjY3ZWEiLCJlbWFpbCI6InBldGVyQGV4YW1wbGUuY29tIiwicm9sZSI6IlVTRVIiLCJpYXQiOjE3NTAxNDc0NTUsImV4cCI6MTc1MDE1MTA1NX0.IrbmHWITzK00FhzaN12DR-X5NPjZzZWm7J2bXtY-tcU

@refreshToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3MjQ0YTlmMC00YjA3LTRiYTUtYWJmOC1mMmU1OWVmYjY3ZWEiLCJlbWFpbCI6InBldGVyQGV4YW1wbGUuY29tIiwicm9sZSI6IlVTRVIiLCJpYXQiOjE3NTAxNDc0NTUsImV4cCI6MTc1MDc1MjI1NX0.9rfWpbd2V3_NaowZ6Lq4ANwT88ZFIW3YhOBs5-sA5Qs

### Register a new user
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "email": "peters@example.com",
  "password": "SecurePass123!",
  "confirmPassword": "SecurePass123!",
  "name": "peter"
}

### Login with email and password
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "peter@example.com",
  "password": "testpasswordpeter"
}

### Refresh access token
POST http://localhost:3000/auth/refresh
Content-Type: application/json
Authorization: Bearer {{refreshToken}}

{}

### Get current user profile
GET http://localhost:3000/auth/me
Authorization: Bearer {{accessToken}}

### Logout
POST http://localhost:3000/auth/logout
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "refreshToken": "{{refreshToken}}"
}

### Logout from all sessions
POST http://localhost:3000/auth/logout-all
Content-Type: application/json
Authorization: Bearer {{accessToken}}
