
POST http://localhost:3000/project?userEmail=admin@example.com
Content-Type: application/json

{
  "title": "Test Project",
  "description": "A sample project",
  "duedate": "2025-07-01T00:00:00.000Z"
}

### Get all projects for a user
GET http://localhost:3000/project?userEmail=admin@example.com

### Assign a user to a project
POST http://localhost:3000/project/assign?userEmail=admin@example.com
Content-Type: application/json

{
  "projectTitle": "Test Project",
  "userId": "357c0841-763e-4e56-92bc-eb192020b52a"
}



##### Get all projects assigned to a user
GET http://localhost:3000/project/assigned?userId=user123

### Complete a project
POST http://localhost:3000/project/complete
Content-Type: application/json

{
  "userId": "user123"
}


### Path: project-management-backend/restclient/user.http
POST http://localhost:3000/users
Content-Type: application/json

{
  "email": "user@example.com",
  "password": "user123",
  "name": "Regular User"
}


### Get all users
GET http://localhost:3000/users

### Get a user by id
GET http://localhost:3000/users/357c0841-763e-4e56-92bc-eb192020b52a


### Update a user
PUT http://localhost:3000/users/357c0841-763e-4e56-92bc-eb192020b52a
Content-Type: application/json

{
  "email": "user@example.com",
  "password": "user123",
  "name": "Regular User2"
}

### Delete a user
DELETE http://localhost:3000/users/1749980213261

